name: CI - Java
on:
  push:
  pull_request:
jobs:
  java:
    name: ui test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Test with TestNG
        run: |
          cd java
          mvn test
