name: CI - Java
on:
  push:
  pull_request:
jobs:
  java:
    name: ui test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Install chrome
        uses: nanasess/setup-chromedriver@v1.0.7
      - name: Setup chromedriver
        run: chromedriver --url-base=/wd/hub &
      - name: Start XVFB
        run: Xvfb :99 &
      - name: Test with TestNG
        run: |
          cd java
          mvn test
        env:
          DISPLAY: :99
